# Mostly generated by flyctl launch
ARG GO_VERSION=1
FROM golang:${GO_VERSION}-alpine as builder
ENV CGO_ENABLED="0"

COPY . /usr/src/url-shortener/
WORKDIR /usr/src/url-shortener
RUN go build -v -o /url-shortener .


FROM gcr.io/distroless/static-debian12:nonroot

ENV PORT="8080"

COPY --from=builder /url-shortener /usr/local/bin/url-shortener
COPY ./links.txt /links.txt

CMD ["url-shortener", "-serve", "-linkfile", "/links.txt"]
